[env:tc001]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 460800
upload_speed = 460800
; CORE_DEBUG_LEVEL=0: логи ядра не должны попадать в UART0 — это наш канал данных
build_flags =
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  fastled/FastLED@3.6.0
  marcmerlin/FastLED NeoMatrix@^1.2
  marcmerlin/Framebuffer GFX@^1.1
  adafruit/Adafruit GFX Library@^1.11.9
  bblanchon/ArduinoJson@^7.2.0
